name: image_finder_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  auto_route: ^10.1.0+1
  dio: ^5.8.0+1
  sqflite: ^2.4.2
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.1
  path: ^1.9.1
  path_provider: ^2.1.5
  toastification: ^3.0.3
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.3
  json_serializable: ^6.9.5
  auto_route_generator: ^10.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
